### PR TITLE
Kevin

### PR DESCRIPTION
**Pull request by kevinbenac**
Hi Elizabeth,

Here is the modified version of the getFeatures file. Please let me know if you have any questions/comments.

All the best,
Kevin

### CODE REVIEW

**Comment by epurdom** [comment]
Thanks Kevin, I will try to look at it before the meeting Wednesday. Elizabeth

**Comment by epurdom** [comment]
Kevin, I've looked at the commits and made changes under a new branch on clusterExperiment entitled kevinbenac-Kevin. I have the following general comments
1. Davide and I want to change the the input arguments to be `DEMethod` and `weights` rather than `isCount` and `weights`. `weights` would only (right now) be used for the `edgeR` method. But it also means that the `edgeR` method has to work with weights=NULL. I have put in code reflecting this, but you need to check whether this code actually works with weights=NULL
2. As I noted on slack, the function `glmWeightedF` doesn't appear to be a function in `edgeR`. I know this is the code in the `zinbwave` documentation. @drisso where does this come from? Is it out of date? We need to check this.
3. You should rely on `topTags` in edgeR to return results, and then manipulate them to have the same columns as the results of `topTable` in limma (i.e. exactly the same column names). Indeed it would make sense to make a small function that does this. The reason for this is two-fold. The first is that you can rely on `topTags` to make the correct calculations, and the second is that it makes it much easier to maintain the code if it is simple and mirrors the limma code.
4. We need some unit tests to make sure that we are getting out what we expect and that they match if we manually ran it. You should look under the tests folder (`test_getBestFeatures.R`) for what already exists, and add new tests. The idea is to use the existing simple objects as input data (they are small objects that will work quickly). Just random weights. The ideas is to run the code, not make sense.

**Comment by epurdom** [comment]
If you make further changes you should start from this new branch...

**Comment by kevinbenac** [comment]
Hi Elizabeth,


Thank you for these comments! For 2., the glmWeightedF is a function from zinbwave. I’m going to work on the other points today and get back to you tomorrow during the BRAIN meeting.

Best,
Kevin

**Pull request merged**
